_wandb:
    value:
        cli_version: 0.24.0
        e:
            ok10cvybt13der2jpfyd9on87bit7ae9:
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "39035613184"
                email: pengularity@gmail.com
                executable: /home/pengu/projects/medical-ai-spleen-segmentation-MONAI/.venv/bin/python3
                git:
                    commit: 5c6ae1100d6bf43e78c552a3a9c36d25021a85b5
                    remote: https://github.com/Pengularity/medical-ai-spleen-segmentation-MONAI.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-02991ec2-d964-60a6-aa05-64e6419c99ff
                host: DESKTOP-0AIFO9T
                memory:
                    total: "12502708224"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/pengu/projects/medical-ai-spleen-segmentation-MONAI/src/train.py
                python: CPython 3.10.17
                root: /home/pengu/projects/medical-ai-spleen-segmentation-MONAI
                startedAt: "2026-01-29T06:06:59.571792Z"
                writerId: ok10cvybt13der2jpfyd9on87bit7ae9
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 41
                - 48
            "2":
                - 1
                - 41
                - 48
            "3":
                - 2
                - 13
            "4": 3.10.17
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
